### ISSUE TITLE
Error:(123, 0) Could not find property 'mavenUser' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@1b6c0a5a.

### ISSUE THREAD

**Issue by yorkwang** [exallium/RxRecyclerView#4]

**Comment by exallium** [comment]
Hi,

This is happening because you're trying to deploy the library to Bintray without maven credentials set up in `~/.gradle/gradle.properties`

If you really want to host your own version of this library, you will need to add `mavenUser` and `mavenPassword` as fit.

This is non-essential to the operation of the library, and I, of course, am very unwilling to provide personal details ;)

http://stackoverflow.com/questions/12749225/where-to-put-gradle-configuration-i-e-credentials-that-should-not-be-committe

If you believe that this is an error, or this error is blocking you from using the library as intended, please let me know.  Providing a description would be very helpful.

Thanks.
Alex.
